In [1]:
import pandas as pd

In [2]:
# Criar um dataframe Pandas a partir dos dados da amostra do Orange
dados = pd.read_csv('/content/SAMPLE_ENERGY_DATA.csv')

In [7]:
type(dados)

pandas.core.frame.DataFrame

# **ANÁLISE EXPLORATÓRIA PRELIMINAR**

In [3]:
# Visualizar registros iniciais
dados.head()

,Date,Time,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3
0,2008-12-01 00:00:00,2026-08-03 09:44:00,1.502,0.074,240.17,6.4,0,0,18
1,2006-12-17 00:00:00,2026-08-03 23:39:00,0.374,0.264,245.50,1.8,0,2,0
2,2009-06-03 00:00:00,2026-08-03 17:01:00,0.620,0.300,239.85,3.0,0,1,1
3,2007-05-09 00:00:00,2026-08-03 05:53:00,0.280,0.200,235.72,1.4,0,0,0
4,2008-12-14 00:00:00,2026-08-03 02:57:00,1.372,0.054,243.95,5.6,0,0,18

In [4]:
# Dimensões do dataframe
dados.shape

(40986, 9)

In [10]:
dados.shape[0]

40986

In [5]:
# Informações dos atributos
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40986 entries, 0 to 40985
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Date                   40986 non-null  object
 1   Time                   40986 non-null  object
 2   Global_active_power    40986 non-null  float64
 3   Global_reactive_power  40986 non-null  float64
 4   Voltage                40986 non-null  float64
 5   Global_intensity       40986 non-null  float64
 6   Sub_metering_1         40986 non-null  int64
 7   Sub_metering_2         40986 non-null  int64
 8   Sub_metering_3         40986 non-null  int64
dtypes: float64(4), int64(3), object(2)
memory usage: 2.8+ MB

In [6]:
# Estatísticas descritivas dos atributos numéricos
# contagem, min, max, média, mediana, desvio padrão, distribuição dos quartis
dados.describe()

,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3
count,40986.000000,40986.000000,40986.000000,40986.000000,40986.000000,40986.000000,40986.000000
mean,1.098045,0.125255,240.843132,4.653838,1.166984,1.280120,6.532816
std,1.059122,0.112929,3.242971,4.448916,6.276977,5.751622,8.474909
min,0.076000,0.000000,225.900000,0.200000,0.000000,0.000000,0.000000
25%,0.310000,0.050000,239.000000,1.400000,0.000000,0.000000,0.000000
50%,0.613000,0.102000,241.020000,2.600000,0.000000,0.000000,1.000000
75%,1.536000,0.196000,242.870000,6.400000,0.000000,1.000000,17.000000
max,10.290000,1.000000,253.320000,44.600000,80.000000,77.000000,31.000000

In [11]:
# Rótulos das colunas
dados.columns

Index(['Date', 'Time', 'Global_active_power', 'Global_reactive_power',
       'Voltage', 'Global_intensity', 'Sub_metering_1', 'Sub_metering_2',
       'Sub_metering_3'],
      dtype='object')

In [15]:
# Renomear os rótulos das colunas
# Criar um dicionário:
# Chaves ---> rótulos atuais
# Valores ---> rótulos desejados
dados.rename({'Date': 'Data',
              'Time': 'Hora',
              'Global_active_power': 'Potencia_Ativa',
              'Global_reactive_power': 'Potencia_Reativa',
              'Voltage': 'Tensao',
              'Global_intensity': 'Corrente',
              'Sub_metering_1': 'Consumo_1',
              'Sub_metering_2': 'Consumo_2',
              'Sub_metering_3': 'Consumo_3'}, axis=1,inplace=True)
dados.head()

,Data,Hora,Potencia_Ativa,Potencia_Reativa,Tensao,Corrente,Consumo_1,Consumo_2,Consumo_3
0,2008-12-01 00:00:00,2026-08-03 09:44:00,1.502,0.074,240.17,6.4,0,0,18
1,2006-12-17 00:00:00,2026-08-03 23:39:00,0.374,0.264,245.50,1.8,0,2,0
2,2009-06-03 00:00:00,2026-08-03 17:01:00,0.620,0.300,239.85,3.0,0,1,1
3,2007-05-09 00:00:00,2026-08-03 05:53:00,0.280,0.200,235.72,1.4,0,0,0
4,2008-12-14 00:00:00,2026-08-03 02:57:00,1.372,0.054,243.95,5.6,0,0,18

In [16]:
dados.columns

Index(['Data', 'Hora', 'Potencia_Ativa', 'Potencia_Reativa', 'Tensao',
       'Corrente', 'Consumo_1', 'Consumo_2', 'Consumo_3'],
      dtype='object')

In [17]:
# Criar dataframe 'df1' sem as colunas Data e Hora
df1 = dados.drop(columns=['Data', 'Hora'])
df1.head()

,Potencia_Ativa,Potencia_Reativa,Tensao,Corrente,Consumo_1,Consumo_2,Consumo_3
0,1.502,0.074,240.17,6.4,0,0,18
1,0.374,0.264,245.50,1.8,0,2,0
2,0.620,0.300,239.85,3.0,0,1,1
3,0.280,0.200,235.72,1.4,0,0,0
4,1.372,0.054,243.95,5.6,0,0,18

In [ ]:
tensao = dados['Tensao']
tensao

In [20]:
type(dados)

pandas.core.frame.DataFrame

In [19]:
type(tensao)

pandas.core.series.Series

In [21]:
# Criar dataframe 'df2' somente com as colunas de Tensão e Corrente
df2 = dados[['Tensao', 'Corrente']]
df2.head()

   Tensao  Corrente
0  240.17       6.4
1  245.50       1.8
2  239.85       3.0
3  235.72       1.4
4  243.95       5.6

In [22]:
dados.head()

,Data,Hora,Potencia_Ativa,Potencia_Reativa,Tensao,Corrente,Consumo_1,Consumo_2,Consumo_3
0,2008-12-01 00:00:00,2026-08-03 09:44:00,1.502,0.074,240.17,6.4,0,0,18
1,2006-12-17 00:00:00,2026-08-03 23:39:00,0.374,0.264,245.50,1.8,0,2,0
2,2009-06-03 00:00:00,2026-08-03 17:01:00,0.620,0.300,239.85,3.0,0,1,1
3,2007-05-09 00:00:00,2026-08-03 05:53:00,0.280,0.200,235.72,1.4,0,0,0
4,2008-12-14 00:00:00,2026-08-03 02:57:00,1.372,0.054,243.95,5.6,0,0,18

In [25]:
# Criar 'df3' a partir de 'dados' somente com as 4 primeiras colunas
# Índices: 0, 1, 2, 3
df3 = dados.iloc[:, 0:4]
df3.head()

                  Data                 Hora  Potencia_Ativa  Potencia_Reativa
0  2008-12-01 00:00:00  2026-08-03 09:44:00           1.502             0.074
1  2006-12-17 00:00:00  2026-08-03 23:39:00           0.374             0.264
2  2009-06-03 00:00:00  2026-08-03 17:01:00           0.620             0.300
3  2007-05-09 00:00:00  2026-08-03 05:53:00           0.280             0.200
4  2008-12-14 00:00:00  2026-08-03 02:57:00           1.372             0.054

In [27]:
dados.shape[0]

40986

In [26]:
# Calcular a demanda máxima (Potência Ativa, em kW)
PMAX = dados['Potencia_Ativa'].max()
print(f'A demanda máxima de potência é {PMAX:.2f} kW')

A demanda máxima de potência é 10.29 kW

In [32]:
# Calcular limiar de 70% da demanda máxima (PMAX)
P70 = 0.7 * PMAX
print(f'O limiar de 70% da demanda máxima é {P70:.2f} kW')

O limiar de 70% da demanda máxima é 7.20 kW

In [ ]:
# Quantos consumidores estão com demanda acima de 70%
# Criar um dataframe 'df4' somente com as colunas de tensão, corrente e potências
# e registros de consumidores com demanda energética acima de 70% de PMAX

In [28]:
dados.columns

Index(['Data', 'Hora', 'Potencia_Ativa', 'Potencia_Reativa', 'Tensao',
       'Corrente', 'Consumo_1', 'Consumo_2', 'Consumo_3'],
      dtype='object')

In [29]:
df4 = dados[['Tensao', 'Corrente', 'Potencia_Ativa', 'Potencia_Reativa']]
df4.head()

   Tensao  Corrente  Potencia_Ativa  Potencia_Reativa
0  240.17       6.4           1.502             0.074
1  245.50       1.8           0.374             0.264
2  239.85       3.0           0.620             0.300
3  235.72       1.4           0.280             0.200
4  243.95       5.6           1.372             0.054

In [30]:
df4.shape[0]

40986

In [33]:
df5 = df4[df4['Potencia_Ativa'] > P70]
df5.head()

       Tensao  Corrente  Potencia_Ativa  Potencia_Reativa
3132   236.23      36.0           8.540             0.238
3630   231.50      35.6           8.278             0.088
4606   231.34      32.0           7.394             0.118
5023   234.56      31.8           7.468             0.184
10339  236.45      33.8           8.026             0.066

In [34]:
df5.shape[0]

23

In [35]:
print(f'Foram encontrados {df5.shape[0]} consumidores com demanda energética acima de 70% de PMAX')

Foram encontrados 23 consumidores com demanda energética acima de 70% de PMAX